.bowerrc
app/Http/Controllers/HomeController.php
app/Http/Kernel.php
app/Http/Middleware/Locale.php
app/Models/Comment.php
app/Models/Education.php
app/Models/EmployeeProfile.php
app/Models/EmployerProfile.php
app/Models/Experience.php
app/Models/Field.php
app/Models/Job.php
app/Models/User.php
bower.json
config/app.php
resources/lang/en/messages.php
resources/lang/vi/messages.php
routes/web.php

- [#39328](https://edu-redmine.sun-asterisk.vn/issues/39328)
- [#39329](https://edu-redmine.sun-asterisk.vn/issues/39329)
Init models and relationships
Init Localization

Init models and init localization

---

database/migrations/2014_10_12_000000_create_users_table.php
database/migrations/2021_08_02_023759_create_employee_profiles_table.php
database/migrations/2021_08_02_032502_create_employer_profiles_table.php
database/migrations/2021_08_02_035347_create_education_table.php
database/migrations/2021_08_02_035358_create_experiences_table.php
database/migrations/2021_08_02_041103_create_fields_table.php
database/migrations/2021_08_02_041112_create_jobs_table.php
database/migrations/2021_08_02_084257_create_comments_table.php
database/migrations/2021_08_02_084506_create_employee_profile_job.php

- [#39172](https://edu-redmine.sun-asterisk.vn/issues/39172)
Add migrations
Add migrations for the following tables:
* users
* employee_profiles
* employer_profiles
* educations
* experiences
* jobs
* fields
* comments
* employee_profile_job

Add migrations

---

app/Http/Controllers/Auth/ConfirmPasswordController.php
app/Http/Controllers/Auth/LoginController.php
app/Http/Kernel.php
app/Http/Middleware/PreventBackHistory.php
composer.json
composer.lock
config/user.php
package-lock.json
package.json
public/mix-manifest.json
resources/js/bootstrap.js
resources/sass/_variables.scss
resources/sass/app.scss
resources/views/auth/login.blade.php
routes/web.php
webpack.mix.js

- [#39331](https://edu-redmine.sun-asterisk.vn/issues/39331)
- Login, Logout
- Using laravel/ui: https://github.com/laravel/ui

Add laravel auth

---

app/Http/Controllers/EmployeeProfileController.php
app/Models/EmployeeProfile.php
public/mix-manifest.json
resources/css/main.css
resources/css/style_cv.css
resources/js/my_cv.js
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/views/employee/cv_template1.blade.php
resources/views/employee/cv_template2.blade.php
resources/views/employee/my_cv.blade.php
resources/views/layouts/cv.blade.php
routes/web.php
webpack.mix.js

- [#39180](https://edu-redmine.sun-asterisk.vn/issues/39180)
- Make CV Template
- Allows users to edit CV, drag and drop, style CV by themselves
- Allows users to download CV
- Using a library called Grapesjs to make draggable and droppable elements: _https://grapesjs.com/docs/_

CV Builder and CV Download

---

app/Http/Controllers/EmployerProfileController.php
app/Http/Requests/EmployerUpdateRequest.php
app/Models/EmployerProfile.php
app/Policies/EmployerProfilePolicy.php
app/Providers/AuthServiceProvider.php
resources/css/main.css
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/lang/vi/validation.php
resources/views/employee/edit_profile.blade.php
resources/views/employer/edit_profile.blade.php
resources/views/employer/profile.blade.php
resources/views/layouts/master.blade.php
routes/web.php

- [#39182](https://edu-redmine.sun-asterisk.vn/issues/39182)
Add profile editing feature for employer
Validate user input using form request.
Authorize user using policy.
* Edit profile
* View profile

Add profile editing feature for employer

---

app/Http/Controllers/EducationController.php
app/Http/Controllers/EmployeeProfileController.php
app/Http/Controllers/ExperienceController.php
app/Http/Requests/StoreEducationRequest.php
app/Http/Requests/StoreExperienceRequest.php
app/Http/Requests/UpdateEmployeeProfileRequest.php
app/Models/User.php
app/Policies/EducationPolicy.php
app/Policies/EmployeeProfilePolicy.php
app/Policies/ExperiencePolicy.php
app/Policies/JobPolicy.php
app/Providers/AuthServiceProvider.php
routes/web.php

- [#39175](https://edu-redmine.sun-asterisk.vn/issues/39175)
- Authorization using gates and policies

Add authorization

---

app/Http/Controllers/JobController.php
app/Http/Requests/JobCreateOrUpdateRequest.php
app/Models/Job.php
app/Rules/JobFieldIdAvailable.php
app/Rules/JobTypeAvailable.php
config/user.php
resources/js/create_summernote.js
resources/lang/en/messages.php
resources/lang/en/validation.php
resources/lang/vi/messages.php
resources/lang/vi/validation.php
resources/views/job/create.blade.php
resources/views/job/edit.blade.php
resources/views/layouts/main.blade.php
routes/web.php
webpack.mix.js

- [#39184](https://edu-redmine.sun-asterisk.vn/issues/39184)
Add job-creating, editing, deleting, hiding features
* Create job
* Edit job

Add job creating, editing, deleting, hiding features

---

app/Http/Controllers/ApplyJobController.php
app/Http/Controllers/EmployeeProfileController.php
app/Http/Requests/StoreApplicationFormRequest.php
app/Models/EmployeeProfile.php
app/Models/Job.php
config/user.php
database/migrations/2021_08_10_093130_add_cover_letter_to_employee_profile_job_table.php
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/views/employee/applied_jobs.blade.php
resources/views/job/application_form.blade.php
resources/views/layouts/main.blade.php
resources/views/layouts/master.blade.php
resources/views/layouts/user_header.blade.php
routes/web.php

- [#39185](https://edu-redmine.sun-asterisk.vn/issues/39185)
- Apply Job ad Attach CV
- Update and delete application forms

Apply Jobs

---

app/Http/Controllers/Auth/LoginController.php
app/Http/Controllers/HomeController.php
public/mix-manifest.json
resources/css/main.css
resources/js/main.js
resources/js/upload.js
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/views/employee/edit_profile.blade.php
resources/views/employee/profile.blade.php
resources/views/inactive.blade.php
resources/views/layouts/employee_nav.blade.php
resources/views/layouts/header.blade.php
resources/views/layouts/main.blade.php
resources/views/layouts/master.blade.php
resources/views/layouts/user_header.blade.php
routes/web.php
webpack.mix.js

- [#39788](https://edu-redmine.sun-asterisk.vn/issues/39788)
- Add routing among screens
- Fix some bugs

Add routing

---

app/Http/Controllers/EmployerProfileController.php
app/Http/Controllers/JobController.php
app/Models/EmployerProfile.php
resources/css/main.css
resources/js/candidates.js
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/views/employer/jobs.blade.php
resources/views/job/candidates.blade.php
resources/views/job/detail.blade.php
resources/views/layouts/employee_header.blade.php
resources/views/layouts/employer_header.blade.php
resources/views/layouts/employer_nav.blade.php
resources/views/layouts/main.blade.php
resources/views/layouts/master.blade.php
routes/web.php
webpack.mix.js

- [#39187](https://edu-redmine.sun-asterisk.vn/issues/39187)
Add candidates approval feature
* View created jobs
* View candidates for a job

Add candidates approval feature

---

app/Http/Controllers/EmployerProfileController.php
app/Models/EmployerProfile.php
config/user.php
resources/css/main.css
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/views/employer/profile.blade.php

- [#39829](https://edu-redmine.sun-asterisk.vn/issues/39829)
Add recently posted jobs to employer profile page

Add recently posted jobs to employer profile page

---

app/Http/Controllers/JobController.php
public/mix-manifest.json
resources/css/main.css
resources/js/admin.js
resources/views/admin/jobs.blade.php
resources/views/employer/jobs.blade.php
routes/web.php

- [#39193](https://edu-redmine.sun-asterisk.vn/issues/39193)
Add jobs management for admin
Using Datatable to show jobs list

Add jobs management for admin

---

app/Http/Controllers/CommentController.php
app/Models/Comment.php
app/Models/Job.php
app/Policies/CommentPolicy.php
public/mix-manifest.json
resources/css/main.css
resources/js/comment.js
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/views/job/comments.blade.php
resources/views/job/detail.blade.php
resources/views/layouts/main.blade.php
routes/web.php
webpack.mix.js

- [#39186](https://edu-redmine.sun-asterisk.vn/issues/39186)
Add comment feature
Create a comment section on the job detail page.
Use ajax to get comments, edit comments, delete comments.

Add comment feature

---

app/Http/Kernel.php
app/Http/Middleware/AddCSPHeader.php

- [#40172](https://edu-redmine.sun-asterisk.vn/issues/40172)
Add XSS protection
Create AddCSPHeader middleware to add Content-Security-Policy header to each response.

Add XSS protection

---

app/Http/Controllers/HomeController.php
app/Http/Controllers/JobController.php
app/Http/Controllers/UserController.php
app/Http/Requests/JobCreateOrUpdateRequest.php
app/Models/Job.php
database/migrations/2021_08_14_130058_alter_jobs_table.php
resources/views/admin/dashboard.blade.php
resources/views/admin/jobs.blade.php
resources/views/auth/login.blade.php
resources/views/employer/edit_profile.blade.php
resources/views/employer/profile.blade.php
resources/views/job/create.blade.php
resources/views/job/detail.blade.php
resources/views/layouts/employee_header.blade.php
resources/views/layouts/employee_nav.blade.php
resources/views/layouts/employer_header.blade.php
routes/web.php

- [#40169](https://edu-redmine.sun-asterisk.vn/issues/40169)
- Admin Dashboard
- Fix edit company profile

Admin dashboard

---

app/Http/Controllers/UserController.php
app/Http/Kernel.php
app/Http/Requests/ChangeAccountInfoRequest.php
resources/css/main.css
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/views/layouts/employee_header.blade.php
resources/views/layouts/employee_nav.blade.php
resources/views/layouts/employer_header.blade.php
resources/views/layouts/employer_nav.blade.php
resources/views/user/account_info.blade.php
routes/web.php

- [#40171](https://edu-redmine.sun-asterisk.vn/issues/40171)
Add account information updating feature

Add account information updating feature

---

app/Http/Controllers/ApplyJobController.php
app/Http/Controllers/EmployerProfileController.php
app/Http/Requests/UpdateEmployeeProfileRequest.php
app/Providers/AuthServiceProvider.php
resources/views/employee/applied_jobs.blade.php
resources/views/employee/edit_profile.blade.php
resources/views/employee/education.blade.php
resources/views/employee/experience.blade.php
resources/views/employer/edit_profile.blade.php
resources/views/employer/jobs.blade.php
resources/views/job/candidates.blade.php
resources/views/job/create.blade.php
resources/views/layouts/cv.blade.php
resources/views/layouts/employee_header.blade.php
resources/views/layouts/homepage.blade.php
routes/web.php

- [#40173](https://edu-redmine.sun-asterisk.vn/issues/40173)
- Fix candidates list
- Approve or reject candidates
- Fix education and experience page

Approve candidate

---

app/Http/Controllers/EducationController.php
app/Providers/AppServiceProvider.php
app/Repositories/Education/EducationRepository.php
app/Repositories/Education/EducationRepositoryInterface.php
app/Repositories/Repository.php
app/Repositories/RepositoryInterface.php
routes/web.php

- [#39174](https://edu-redmine.sun-asterisk.vn/issues/39174)
- Set up base repository
- Education Repository

Base Repository and Education Repository

---

tests/ModelTestCase.php
tests/Unit/Models/CommentTest.php
tests/Unit/Models/EducationTest.php
tests/Unit/Models/EmployeeProfileTest.php
tests/Unit/Models/EmployerProfileTest.php

- [#40841](https://edu-redmine.sun-asterisk.vn/issues/40841)
Add unit tests for the following models:
* Comment
* Education
* EmployeeProfile
* EmployerProfile

Add unit tests for some models

---

app/Http/Controllers/EducationController.php
app/Repositories/Repository.php
database/factories/EducationFactory.php
database/factories/EmployeeProfileFactory.php
database/factories/UserFactory.php
tests/Unit/Http/Controllers/EducationControllerTest.php

- [#40890](https://edu-redmine.sun-asterisk.vn/issues/40890)
- Test Education Controller

Test EducationController

---

app/Http/Controllers/ApplyJobController.php
app/Http/Controllers/EmployerProfileController.php
app/Http/Controllers/HomeController.php
app/Http/Controllers/JobController.php
app/Http/Requests/ChangeJobApplicationStatusRequest.php
app/Models/Job.php
app/Providers/AppServiceProvider.php
app/Repositories/EmployeeProfile/EmployeeProfileRepository.php
app/Repositories/EmployeeProfile/EmployeeProfileRepositoryInterface.php
app/Repositories/EmployerProfile/EmployerProfileRepository.php
app/Repositories/EmployerProfile/EmployerProfileRepositoryInterface.php
app/Repositories/Job/JobRepository.php
app/Repositories/Job/JobRepositoryInterface.php
app/Repositories/Repository.php
app/Repositories/RepositoryInterface.php
resources/views/admin/employer.blade.php

- [#40953](https://edu-redmine.sun-asterisk.vn/issues/40953)
Refactor Controllers by using Repositories
Implement the following Repositories:
* EmployeeProfileRepository
* EmployerProfileRepository
* JobRepository
Refactor the following Controllers by using the above Repositories:
* ApplyJobController
* EmployerProfileController
* HomeController
* JobController

Refactor Controllers by using Repositories

---

app/Http/Controllers/EmployeeProfileController.php
app/Http/Controllers/ExperienceController.php
app/Http/Controllers/SearchController.php
app/Http/Controllers/UserController.php
app/Http/Requests/ChangeImageRequest.php
app/Providers/AppServiceProvider.php
app/Repositories/EmployeeProfile/EmployeeProfileRepository.php
app/Repositories/EmployeeProfile/EmployeeProfileRepositoryInterface.php
app/Repositories/EmployerProfile/EmployerProfileRepository.php
app/Repositories/EmployerProfile/EmployerProfileRepositoryInterface.php
app/Repositories/Experience/ExperienceRepository.php
app/Repositories/Experience/ExperienceRepositoryInterface.php
app/Repositories/Field/FieldRepository.php
app/Repositories/Field/FieldRepositoryInterface.php
app/Repositories/Job/JobRepository.php
app/Repositories/Job/JobRepositoryInterface.php
app/Repositories/User/UserRepository.php
app/Repositories/User/UserRepositoryInterface.php

- [#40951](https://edu-redmine.sun-asterisk.vn/issues/40951)
- Change to user repository

Change to use Repository

---

app/Events/JobApplicationStatusChanged.php
app/Http/Controllers/ApplyJobController.php
app/Listeners/SendJobApplicationApprovalEmail.php
app/Mail/JobApplicationApproved.php
app/Mail/JobApplicationRejected.php
app/Providers/EventServiceProvider.php
app/Repositories/EmployeeProfile/EmployeeProfileRepository.php
resources/js/candidates.js
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/views/emails/jobs/applications/approved.blade.php
resources/views/emails/jobs/applications/rejected.blade.php
resources/views/job/candidates.blade.php

- [#41129](https://edu-redmine.sun-asterisk.vn/issues/41129)
Add Sending job application result email feature
Using Event and Listener.
Trigger the event when the job application status is updated.

Add Sending job application result email feature

---

app/Events/MessageSent.php
app/Http/Requests/SendMessageRequest.php
app/Models/Conversation.php
app/Models/Message.php
composer.json
composer.lock
config/app.php
config/user.php
database/migrations/2021_09_01_052738_create_conversations_table.php
database/migrations/2021_09_01_052749_create_messages_table.php
package-lock.json
package.json
resources/js/bootstrap.js
resources/js/chat.js
resources/views/layouts/message.blade.php
routes/channels.php

- [#41144](https://edu-redmine.sun-asterisk.vn/issues/41144)
- Set up chat
- Init models
- create migrations
- configuration pusher, laravel echo..

Chat Configuration

---

app/Http/Controllers/HomeController.php
app/Models/Job.php
app/Repositories/Job/JobRepository.php
app/Repositories/Job/JobRepositoryInterface.php
public/mix-manifest.json
resources/js/candidates.js
resources/js/chart.js
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/views/admin/statistic.blade.php
resources/views/job/candidates.blade.php
resources/views/layouts/admin.blade.php
resources/views/layouts/employee_nav.blade.php
routes/web.php
tests/Unit/Models/JobTest.php
webpack.mix.js

- [#41521](https://edu-redmine.sun-asterisk.vn/issues/41521)
- Use char.js for statistic

Use chart.js for job statistics

---

app/Http/Controllers/HomeController.php
app/Http/Controllers/MessageController.php
database/factories/ConversationFactory.php
database/factories/EmployerProfileFactory.php
database/factories/FieldFactory.php
database/factories/MessageFactory.php
routes/web.php
tests/Unit/Events/JobApplicationStatusChangedTest.php
tests/Unit/Events/MessageSentTest.php
tests/Unit/Http/Controllers/HomeControllerTest.php
tests/Unit/Http/Controllers/MessageControllerTest.php
tests/Unit/Models/ConversationTest.php
tests/Unit/Models/JobTest.php
tests/Unit/Models/MessageTest.php

- [#41593](https://edu-redmine.sun-asterisk.vn/issues/41593)
Test HomeController, MessageController, Message Model, Conversation Model

Unit test for project 2

---

app/Http/Controllers/NotificationController.php
public/mix-manifest.json
resources/css/main.css
resources/js/notification.js
resources/lang/en/messages.php
resources/lang/vi/messages.php
resources/views/layouts/employee_header.blade.php
resources/views/layouts/homepage.blade.php
resources/views/layouts/main.blade.php
resources/views/layouts/master.blade.php
resources/views/layouts/notifications.blade.php
webpack.mix.js

- [#41597](https://edu-redmine.sun-asterisk.vn/issues/41597)
Add notifications feature

Add notifications feature

---

app/Models/EmployeeProfile.php
app/Models/EmployerProfile.php
app/Repositories/User/UserRepository.php
composer.json
composer.lock
config/scout.php

- [#41600](https://edu-redmine.sun-asterisk.vn/issues/41600)
- Using Laravel Scout to increase searching speed.
- Refrences: https://laravel.com/docs/8.x/scout

Search using Laravel Scout

---

app/Console/Kernel.php
app/Jobs/SendRecommendedJobsNotification.php
app/Notifications/JobRecommendation.php
app/Repositories/User/UserRepository.php
app/Repositories/User/UserRepositoryInterface.php
config/user.php
database/migrations/2021_09_08_000918_create_notifications_table.php
routes/channels.php
routes/web.php

- [#41596](https://edu-redmine.sun-asterisk.vn/issues/41596)
Add sending recommended jobs schedule
Create a job for sending notifications.
This job is scheduled weekly.

Add sending recommended jobs schedule

---

app/Http/Controllers/HomeController.php
app/Http/Middleware/Locale.php
app/Listeners/SendJobApplicationApprovalEmail.php
app/Models/User.php
app/Models/UserPreference.php
app/Providers/AppServiceProvider.php
app/Repositories/Repository.php
app/Repositories/RepositoryInterface.php
app/Repositories/UserPreference/UserPreferenceRepository.php
app/Repositories/UserPreference/UserPreferenceRepositoryInterface.php
database/migrations/2021_09_08_042208_create_user_preferences_table.php
tests/Unit/Http/Controllers/HomeControllerTest.php

- [#41601](https://edu-redmine.sun-asterisk.vn/issues/41601)
Add localization for email
* Implement `HasLocalePreference` contract for `User` model.
* Create `user_preferences` table to store the user's preferred locale.
* Implement `ShouldQueue` contract for `SendJobApplicationApprovalEmail`
listener to make this listener should be queued.

Add localization for email
